version: "3.3"
services:
  server:
    container_name: "tournament_server"
    network_mode: "host"
    build: .
    command: go run ./main.go
    ports: 
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    container_name: "tournament_db"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament