version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4

defaults: &defaults
  working_directory: ~/tournament
  docker:
    - image: circleci/golang:1.12-stretch
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: tournament_test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - tournament
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go install tournament
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'

  test:
    <<: *defaults
    steps:
      - attach_workspace:
            at: ~/
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: rm -rf ./databases
      - run: mv ./env/testing/databases ./databases
      - run: echo $PWD
      - run: go test -v -coverprofile=coverage.out -race ./pkg/controllers/api/routers/tournament
      - run: go test -v -coverprofile=coverage.out -race ./pkg/controllers/api/routers/user
      - run: go test -v -coverprofile=coverage.out -race ./pkg/controllers/repositories/postgresql/tournament -cwd="~/tournament"
      - run: go test -v -coverprofile=coverage.out -race ./pkg/controllers/repositories/postgresql/user -cwd="~/tournament"
      - run: go test -v -coverprofile=coverage.out -race ./pkg/usecases/tournament
      - run: go test -v -coverprofile=coverage.out -race ./pkg/usecases/user
      - codecov/upload:
          file: 'coverage.out'

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
