version: 2

defaults: &defaults
  working_directory: ~/tournament
  docker:
    - image: circleci/golang:1.12-stretch
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: tournament_test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: rm -rf ./databases
      - run: mv ./env/testing/databases ./databases
      - run: go install tournament

  test:
    <<: *defaults
    steps:
      - run: 
          name: routers
          command: go test -v -race ./pkg/controllers/api/routers/...
      - run:
          name: postgresql repository
          command: go test -v -race ./pkg/controllers/repositories/postgresql/... -cwd="~/tournament"
      - run:
          name: usecases
          command: go test -v -race ./pkg/usecases/...

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
