version: 2

defaults: &defaults
  working_directory: ~/tournament
  docker:
    - image: circleci/golang:1.12-stretch
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: tournament_test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: rm -rf ./databases
      - run: mv ./env/testing/databases ./databases
      - run: go install tournament

  test:
    <<: *defaults
    steps:
      - run: go test -v -race ./pkg/controllers/api/routers/tournament
      - run: go test -v -race ./pkg/controllers/api/routers/user
      - run: go test -v -race ./pkg/controllers/repositories/postgresql/tournament -cwd="~/tournament"
      - run: go test -v -race ./pkg/controllers/repositories/postgresql/user -cwd="~/tournament"
      - run: go test -v -race ./pkg/usecases/tournament
      - run: go test -v -race ./pkg/usecases/user

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
