version: 2

defaults: &defaults
  working_directory: /tournament

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: ./deploy.sh -l -t

workflows:
  version: 2
  test:
    jobs:
      - test
