version: 2.1

defaults: &defaults
  working_directory: ~/tournament
  docker:
    - image: circleci/golang:1.12
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: tournament_test

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          name: echo
          command: echo $PWD
      - run:
          name: ls
          command: ls -a /
      - run:
          name: deploy
          command: ./deploy.sh -l -t

workflows:
  version: 2
  test:
    jobs:
      - test
