version: 2.1

defaults: &defaults
  working_directory: /go/src/tournament
  docker:
    - image: circleci/golang:1.12
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: tournament_test

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          name: test all
          command: ls -a

workflows:
  version: 2
  test:
    jobs:
      - test
