apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          value: tournament
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        image: postgres:9.6
        name: tournament-db
        ports:
        - containerPort: 31727
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: database-claim
      restartPolicy: Always
      volumes:
      - name: database-claim
        persistentVolumeClaim:
          claimName: database-claim
status: {}
