apiVersion: v1
kind: Service
metadata:
  labels:
    service: database
  name: database
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
    nodePort: 31727
  selector:
    service: database
  type: NodePort
status:
  loadBalancer: {}
