apiVersion: v1
kind: Service
metadata:
  name: psql-service
spec:
  clusterIP: 10.48.9.227
  ports:
    - port: 5432
      targetPort: psql-db-port
      protocol: TCP
  selector:
    app: tournament
    tier: psql-db
