apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: psql-dep
spec:
  replicas: 1
  template:
    metadata:
      name: psql-pod
      labels:
        app: tournament
        tier: psql-db
    spec:
      containers:
        - name: psql-container
          image: postgres:9.6
          env:
            - name: POSTGRES_DB
              value: tournament
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          imagePullPolicy: IfNotPresent
          ports:
            - name: psql-db-port
              containerPort: 5432
          volumeMounts:
            - name: psql-vol
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: psql-vol
          persistentVolumeClaim:
            claimName: psql-pvc
      restartPolicy: Always
