apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: psql-dep
  labels:
    service: psql-np
  namespace: production-cloud
spec:
  replicas: 2
  template:
    metadata:
      name: psql-pod
      labels:
        app: tournament
        tier: psql
    spec:
      containers:
        - name: psql-container
          image: postgres:9.6
          env:
            - name: POSTGRES_DB
              value: tournament
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          ports:
            - containerPort: 5432
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
