apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-dep
spec:
  replicas: 2
  template:
    metadata:
      name: server-pod
      labels:
        app: tournament
        tier: server
    spec:
      containers:
        - name: server-container
          image: plagamedicum/tournament_server:tag
          ports:
            - name: http-server
              containerPort: 8080
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
