apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  containers:
  - image: plagamedicum/tournament_server:tag
    name: tournament-server
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
