apiVersion: v1
kind: Service
metadata:
  name: server-lb
spec:
  type: LoadBalancer
  loadBalancerIP: "35.246.171.29"
  ports:
    - port: 80
      targetPort: http-server
      protocol: TCP
  selector:
    app: tournament
    tier: server
