version: "3"
services:
  database:
    image: postgres
    container_name: "tournament-test-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament_test
    restart: unless-stopped
  server:
    container_name: "tournament-test-server"
    network_mode: "host"
    volumes:
      - ../../pkg:/go/src/tournament/pkg
    build:
      context: ../../
      dockerfile: ./env/testing/Dockerfile
    image: plagamedicum/tournament_test_server:tag
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    restart: on-failure
